// Generated by https://quicktype.io

export interface Planet {
  name: string;
  overview: Geology;
  structure: Geology;
  geology: Geology;
  rotation: string;
  revolution: string;
  radius: string;
  temperature: string;
  images: Images;
}

export interface Geology {
  content: string;
  source: string;
}

export interface Images {
  planet: string;
  internal: string;
  geology: string;
}

export interface PlanetStats {
  rotation: string;
  revolution: string;
  radius: string;
  temperature: string;
}

export type PlanetString =
  | "mercury"
  | "venus"
  | "earth"
  | "mars"
  | "jupiter"
  | "saturn"
  | "uranus"
  | "neptune";
